service: serverless-dynamoosejs

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  fetchUserDetails:
    handler: src/app.lambda_handler
    events:
      - http:
          path: /service/v1/user/{id}
          method: get
          documentation:
            summary: "Get user details"
            description: "Get user details based on userId" 
      - http:
          path: /service/v1/user
          method: get
          documentation:
            summary: "Get users"
            description: "Get users based on joining date" 

custom:
  stage: ${opt:stage, self:provider.stage}